---
version: '3.8'
services:
  node:
    build: ./
    image: viswanathkasi/node
    deploy:
      replicas: 5
    ports:
      - "81:80"
...



#version: '3.8'
#services:
#  node:
#    container_name: node
#    build: .
#    ports:
#      - "81:80"
